from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from jwt_auth_example import views

urlpatterns = [
    path('users', views.TestJWTView.as_view(), name='users'),
    # Use this url to get jwt token to use in subsequent request
    # add jwt token generated by this url in Authentication header with key JWT
    path('api-token-auth/', obtain_jwt_token),
    path('api-token-refresh/', refresh_jwt_token),
]
